[[session]]
name = "dotfiles"
path = "~/dev/dotfiles"
startup_command = "~/dev/dotfiles/bin/tmux_layouts/default.sh"

[[session]]
name = "papi/infra"
path = "~/dev/papi/infra"
startup_command = "~/dev/dotfiles/bin/tmux_layouts/default.sh"

[[session]]
name = "papi/scraper"
path = "~/dev/papi/scraper"
startup_command = "~/dev/dotfiles/bin/tmux_layouts/default.sh"

[[session]]
name = "papi/product-monorepo"
path = "~/dev/papi/product-monorepo"
startup_command = "~/dev/dotfiles/bin/tmux_layouts/default.sh"
