require("sdk.plugins-setup")

require("sdk.core.autocmd")
require("sdk.core.colorscheme")
require("sdk.core.functions")
require("sdk.core.keymaps")
require("sdk.core.options")

require("sdk.plugins.alpha")
require("sdk.plugins.bufferline")
require("sdk.plugins.comment")
require("sdk.plugins.gitsigns")
require("sdk.plugins.indent-blankline")
require("sdk.plugins.lsp.autopairs")
require("sdk.plugins.lsp.lspconfig")
require("sdk.plugins.lsp.mason")
require("sdk.plugins.lualine")
require("sdk.plugins.nvim-cmp")
require("sdk.plugins.nvim-tree")
require("sdk.plugins.project")
require("sdk.plugins.telescope")
require("sdk.plugins.treesitter")
require("sdk.plugins.which-key")
