[tools]
node = "latest"
# go = "latest"
"aqua:neovim" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:jesseduffield/lazydocker" = "latest"
"aqua:derailed/k9s" = "latest"
python = "latest"
"aqua:helm/helm" = "latest"
eza = "latest"
bun = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
