[tools]
node = "latest"
# go = "latest"
"aqua:neovim" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:aristocratos/btop" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:eza-community/eza" = "latest"

[settings]
experimental = true
